### ISSUE TITLE
[suggestion] 可否考虑在releases中增加自动编译？

### ISSUE THREAD

**Issue by goldenapple1** [babalae/better-genshin-impact#429]
- Your suggestions / 你的建议

如题，目前的release频率大概是两周一个release，等到新的正式版再体验的话比较久。但如果使用GitHub Action的build就可以自动编译项目+自动release，可以让愿意更新的人先体验新提交的效果，某种程度上可以增加正式release的稳定性

（不过我也不知道具体是怎么做到的，可能需要作者自己找一找相关视频）

**Comment by huiyadanli** [comment]
暂不不考虑 GitHub Action，软件包体很大大，我们 commit 次数又多，Action容易被误判为滥用导致 repo 封禁（我以前有OpenCV的repo被封过）。

以后可能会回归到 appveyor。或者通过其他方式转移到专门的repo上手动触发CI

**Comment by goldenapple1** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/56142186/4d80ca87-b626-4359-83aa-6d6dc46f7cdd)
还有这种情况？看来是我考虑不周了，不过自动打包的这个需求倒是一直在这儿，那就再说吧。。

**Comment by huiyadanli** [comment]
https://ci.appveyor.com/project/huiyadanli/better-genshin-impact/build/artifacts

已添加 appveyor 进行持续集成

**Comment by huiyadanli** [comment]
```yaml
version: 1.0.{build}
image: Visual Studio 2022
build_script:
- cmd: cmd /c c:\projects\better-genshin-impact\Build\setup_build_for_appveyor.cmd
artifacts:
- path: Build\BetterGI_Setup_*.exe
- path: Build\BetterGI*.7z
```
